SET STATISTICS IO ON
--ISLEMDE GERCEKLESEN PHYSICAL VE LOGICAL ETKINLIK HAKKINDA BILGI GORUNTULER.

SELECT * FROM Sales.Customer WHERE TerrItoryID = 11923
SELECT * FROM Sales.Customer WHERE StoreID = 932 OR TerrItoryID = 11923

--SP_SPACEUSED 'Sales.Customer'
--GECERLI VERI TABANINDAKI BIR TABLO TARAFINDAN KULLANILAN SATIR SAYISINI, DISK ALANINI VB. BILGILERI GORUNTULER.

--INDEX'TEKI UNIQUE IFADESI OLUSTURULAN INDEX TABLOSUNDA ARANAN DEGERIN TEKILLIGINI BILDIRIR.
--DEGERE ULASILDIKTAN SONRA ARAMA TAMAMLANIR.
--UNIQUE OLARAK BELIRLENEN INDEX TABLOSUNA DUPLICATE KAYIT GIRILEMEZ.

--YENI KAYITLAR EKLENDIKÇE INDEX PAGE'LERDE BOZULMA (FRAGMENTATION) GERÇEKLESECEKTIR.
--BU BOZULMAYI DUZELTMEK IÇIN DUZENLI ARALIKLARLA INDEX REBUILD EDILMELIDIR.
--BU SUREYI UZATMAK IÇIN FILL FACTOR OZELLIGINI KULLANMALIYIZ.
--FILL FACTOR PAGE'LERDEKI DOLULUK ORANINI BELIRLER VE YENI KAYITLAR DUZENLI BIR SEKILDE PAGE'LERDEKI BOSLUGA EKLENIR.
--BU SAYEDE PAGE FULNESS DOLANA KADAR FRAGMENTATION'IN ONUNE GEÇILMIS OLUR. 