		-- CREATING SP --
CREATE PROCEDURE SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT
	SELECT @WORKERNAME = WORKERNAME, @WORKERID = ID FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	IF  @WORKERNAME IS NULL
	BEGIN
		RAISERROR('KART GECERSIZ',16,1)
		RETURN
	END

DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO = IOTYPE FROM WORKERTRANSACTIONS
WHERE WORKERID = 1 AND DATE_ <= CONVERT(date,GETDATE())
ORDER BY DATE_ DESC

	IF @LASTIO = @IOTYPE
	BEGIN
		IF @IOTYPE = 'G'
		BEGIN
			RAISERROR('ICERIDESINIZ TEKRAR GIRIS YAPAMAZSINIZ',16,1)
			RETURN
		END
		IF @IOTYPE = 'C'
		BEGIN
			RAISERROR('DISARIDASINIZ TEKRAR CIKIS YAPAMAZSINIZ',16,1)
			RETURN
		END
	END
INSERT INTO WORKERTRANSACTIONS (WORKERID, DATE_, IOTYPE, GATEID)
VALUES (@WORKERID, @DATE, @IOTYPE, @GATEID)

SELECT @WORKERNAME AS WORKERNAME, @DATE AS DATE_, @IOTYPE AS IOTYPE
END
		-- CREATING SP --


  -- USING SP --
EXEC SP_WORKER_INOUT
@WORKERBARCODE = '63355AC4-DB23-40EC-BA6A-2CBD00E6B7E6',
@DATE = '2022-12-23 12:10:15',
@IOTYPE = 'G',
@GATEID = 1
  -- USING SP --


					-- AD HOC QUERY (ANLIK SORGU) --
--YAZILAN SORGUNUN BIR AMAC ICIN YAZILIP COGUNLUKLA DEVAMININ OLMADIGI SORGULARDIR.
--AD HOC QUERY ISLENIRKEN VERI TABANI SUNUCUSUNUN UYGULADIGI ADIMLAR
--1.QUERY
--2.PARSE
--3.OPTIMIZE
--4.COMPILE
--5.EXECUTE
--6.RESULT


				  -- STORED PROCEDURE (YAPISAL YORDAM) --
--HAZIRLAMIS OLDUGUMUZ T-SQL KODUNU KAYIT EDEBILDIGIMIZ SQL KOMUTLARIDIR.
--EXECUTION PLAN CIKARILDIGI VE DERLENDIGI ICIN ILK 4 ASAMAYI ATLAR VE DAHA HIZLI CALISIR.
--5.EXECUTE
--6.RESULT

SELECT * FROM sys.dm_exec_procedure_stats


-- SP'LER # ETIKETIYLE OLUSTURACAGIMIZ GECICI BIR TABLOYA INSERT EDILEBILIR. 
-- BU SEKILDE MUDAHELE EDEMEDIGIMIZ/YRETKIMIZIZ OLMADIGI SP'LERDE ISLEM YAPABILIRIZ.

-- NOT: KULLANILAN TABLOLAR CUSTOMER DATABASE'INDE OLUSTURULAN RASTGELE DEGERLER KULLANILARAK OLUSTURULMUS TABLOLARDIR.