--	SQL SERVER AGENT  --

--SQL SERVER'DA OTOMATIK VE PERIYODIK OLARAK CALISMASINI ISTEDIGIMIZ ISLEMLER ICIN KULLANILIR.
--YEDEK ALMA, INDEX BAKIM PLANLARI, DATABASE SHRINK PLANLARI, VERI AMBARI OLUSTURMA, OTOMATIK RAPORLAR OLUSTURMA, MAIL GONDERME GIBI HIZMETLER ICIN SQL SERVER AGENT KULLANILIR
--JOB, SCHEDULE, ALERT KAVRAMLARI VARDIR.
--TUM KONFIGURASYONUNU MSDB SISTEM DAYABASE'INDE TUTAR.

--	JOB:
--SQL SERVER AGENT SERVISI ARACILIGIYLA PEK COK ISLEMI SIRASIYLA BELIRLENEN PERIYOTLARLA GERCEKLESTIREBILEN BIR ISLEMDIR.

--	SCHEDULE:
--BU ALAN BELIRLEDIGIMIZ ADIMLARIN NE ZAMAN HANGI ARALIKLARLA CALISACAGI BILGILERINI BARINDIRIR.

--	ALERT:
--ALERT JOBUN CALISMA DURUMUNUN TAKIBINI YAPABILMEK ICIN ALARM OLUSTURABILME IMKANI TANIR.
