-- PERIYODIK BAKIM PLANLARI

--INDEX BOZULMALARI:
--SQL SERVER'DA YENI KAYITLAR OLUSTUKCA, SILINDIKCE VE GUNCELLENDIKCE INDEXLER BOZULUR.
--BOZULAN INDEXLERI DUZELTMEK ICIN INDEX REBUILD YA DA INDEX REORGANIZE ISLEMI YAPILIR.

--ISTATISTIK GUNCELLEMELERI
--SQL SERVER'DA SISTEM DOGRU INDEX'I BULABILMEK ICIN ISTATISTIKLERE BAKAR.
--YENI KAYITLAR OLUSTUKCA, SILINDIKCE VE GUNCELLENDIKCE BIR INDEX'TE HANGI KAYDIN NE KADAR OLDUGU DEGISIR.
--ISTATISTIKLER NE KADAR GUNCEL ISE SISTEM DOGRU INDEX'I O KADAR IYI BULUR.

--DATABASE SHRINK:
--SQL SERVER'DA BIR DATABASE'E YENI KAYIT EKLENDIKCE DATABASE BUYUR AMA KAYIT SILINDIKCE KUCULMEZ.
--EGER BUYUYEN BIR VERITABANI KUCULTULMEK ISTENIYORSA SHRINK ISLEMI GERCEKLESTIRILIR.

--DATABASE BACKUP:
--BIR VEYA BIRDEN FAZLA DATABASE YEDEGININ ALINMA ALINMA ISLEMIDIR. 
--FULL, DIFFERENTIAL YA DA TRANSACTION LOG BACKUP OLARAK ISTENEN SEKILDE OTOMATIK OLARAK CALISACAK BACKUP ISLEMIDIR.

--CHECK DATABASE INTEGRITY:
--DATABASE INDEX VE TABLE PAGE'LERDE HERHANGI BIR SIKINTI OLUP OLMADIGINI KONTROL EDER.
--YANI DATABASE'DE BIR BOZUKLUK OLUP OLMADIGINA BAKAR.