-- SQL'DE BACKUP ALMA YONTEMLERI
--1. FULL BACKUP
--2. DIFFERENTIAL BACKUP
--3. TRANSACTION LOG BACKUP 

--	1.FULL BACKUP:
--TUM VERI TABANININ YEDEGININ ALINMASI ISLEMDIDIR.
--SISTEM CALISIRKEN ONLINE OLARAK ALINABILIR.
--SIKISTIRMA PARAMETRESI ILE %95'LERE KADAR SIKISTIRILARAK ALINABILIR.
--SADECE BACKUP ALINAN ZAMANA DONULEBILIR.

--	2.DIFFERENTIAL BACKUP:
--ALINAN SON FULL BACKUP ÝLE DIFFERENTIAL BACKUP ALINAN ZAMAN ARASINDAKI DEGISIM FARKININ ALINDIGI BACKUP TURUDUR.
--FULL BACKUP'A GORE DAHA AZ YER KAPLAR
--SISTEM CALISIRKEN ONLINE OLARAK ALINABILIR.
--SIKISTIRMA PARAMETRESI ILE %95'LERE KADAR SIKISTIRILARAK ALINABILIR.
--SADECE BACKUP ALINAN ZAMANA DONULEBILIR.

--	3.TRANSACTION LOG BACKUP:
--TRANSACTION LOG DOSYASININ YEDKELENMESIDIR.
--EN SON ALINAN BACKUP HANGISI ISE (FULL,DIFF,TLB) ONUNLA ARASINDAKI DEGISIMI ALIR.
--SISTEM CALISIRKEN ONLINE OLARAK ALINABILIR.
--SIKISTIRMA PARAMETRESI ILE %95'LERE KADAR SIKISTIRILARAK ALINABILIR.
--SANIYELIK OLARAK ISTEDIGIMIZ ANA DONME IMKANI VERIR.
--DATA DOSYASINDAN DEGIL LOG DOSYASI UZERINDEN YEDEK ALIR.

