SET STATISTICS IO ON
--Ýþlemde gerçekleþen physical ve logical etkinlik hakkýnda bilgi görüntülemesini saðlar.

SELECT * FROM Sales.Customer WHERE TerritoryID = 11923
SELECT * FROM Sales.Customer WHERE StoreID = 932 OR TerritoryID = 11923

--SP_SPACEUSED 'Sales.Customer'
--Geçerli veritabanýndaki bir tablo tarfýndan kullanýlan satýr sayýsýný, disk alanýný vb. bilgileri görüntüler.

--INDEX'TEKÝ UNIQUE ÝFADESÝ OLUÞTURULAN INDEX TABLOSUNDA ARANAN DEÐERÝN TEKÝLLÝÐÝNÝ BÝLDÝRÝR.
--DEÐERE ULAÞILDIKTAN SONRA ARAMA TAMAMLANIR.
--UNIQUE OLARAK BELÝRLENEN INDEX TABLOSUNA DUPLICATE KAYIT GÝRÝLEMEZ.

--YENÝ KAYITLAR EKLENDÝKÇE INDEX PAGE'LERDE BOZULMA (fragmentation) GERÇEKLEÞECEKTÝR.
--BU BOZULMAYI DÜZELTMEK ÝÇÝN DÜZENLÝ ARALIKLARLA INDEX REBUILD EDÝLMELÝDÝR.
--BU SÜREYÝ UZATMAK ÝÇÝN FILL FACTOR ÖZELLÝÐÝNÝ KULLANMALIYIZ.
--FILL FACTOR PAGE'LERDEKÝ DOLULUK ORANINI BELÝRLER VE YENÝ KAYITLAR DÜZENLÝ BÝR ÞEKÝLDE PAGE'LERDEKÝ BOÞLUÐA EKLENÝR.
--BU SAYEDE PAGE FULNESS DOLANA KADAR FRAGMENTATION'IN ÖNÜNE GEÇÝLMÝÞ OLUR. 